### ISSUE TITLE
Progmem and Flash

### ISSUE THREAD

**Issue by Defragster** [FrankBoesing/MemFile#1]
Should readme note that Progmem and Flash would be READ_ONLY?

For write to those it would take a callable function like you did for SPIFFS

**Comment by FrankBoesing** [comment]
Perhaps a more general advice that it behaves more or less like a pointer, can crash like a pointer, and does not write to flash(like a pointer).

I won't do add more checks or sophisticated code here.  If the MPU does its job, everything is fine.

**Comment by FrankBoesing** [comment]
c0ea921#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by FrankBoesing** [comment]
Is that better? :)

As long flash gets deleted with every upload, it's pretty pointless to use it, anyway.  
When someday this behaviour changes, I'll review this and may provide a "helper"  that allows flash writes (T4 only, then).

But I don't really see that MemFile needs to be able to do that. This is actually a task for other libraries.

**Comment by Defragster** [comment]
Yes.  I was just finding my fork was out of sync and reading - wanted to make sure I was understanding.
